/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/onboarding'
    | '/owner'
    | '/listing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/onboarding'
    | '/owner'
    | '/listing/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/_authenticated/onboarding'
    | '/_authenticated/owner'
    | '/listing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
