/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner/index'
import { Route as AuthenticatedOwnerBookingsRouteImport } from './routes/_authenticated/owner/bookings'
import { Route as AuthenticatedOwnerCustomersRouteImport } from './routes/_authenticated/owner/customers'
import { Route as AuthenticatedOwnerFinanceRouteImport } from './routes/_authenticated/owner/finance'
import { Route as AuthenticatedOwnerListingsRouteImport } from './routes/_authenticated/owner/listings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerBookingsRoute =
  AuthenticatedOwnerBookingsRouteImport.update({
    id: '/owner/bookings',
    path: '/owner/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerCustomersRoute =
  AuthenticatedOwnerCustomersRouteImport.update({
    id: '/owner/customers',
    path: '/owner/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerFinanceRoute =
  AuthenticatedOwnerFinanceRouteImport.update({
    id: '/owner/finance',
    path: '/owner/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerListingsRoute =
  AuthenticatedOwnerListingsRouteImport.update({
    id: '/owner/listings',
    path: '/owner/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/owner/listings': typeof AuthenticatedOwnerListingsRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/owner/listings': typeof AuthenticatedOwnerListingsRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/_authenticated/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/_authenticated/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/_authenticated/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/_authenticated/owner/listings': typeof AuthenticatedOwnerListingsRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/admin'
    | '/onboarding'
    | '/listing/$slug'
    | '/owner/bookings'
    | '/owner/customers'
    | '/owner/finance'
    | '/owner/listings'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/admin'
    | '/onboarding'
    | '/listing/$slug'
    | '/owner/bookings'
    | '/owner/customers'
    | '/owner/finance'
    | '/owner/listings'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/map'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/onboarding'
    | '/listing/$slug'
    | '/_authenticated/owner/bookings'
    | '/_authenticated/owner/customers'
    | '/_authenticated/owner/finance'
    | '/_authenticated/owner/listings'
    | '/_authenticated/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/bookings': {
      id: '/_authenticated/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof AuthenticatedOwnerBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/customers': {
      id: '/_authenticated/owner/customers'
      path: '/owner/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof AuthenticatedOwnerCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/finance': {
      id: '/_authenticated/owner/finance'
      path: '/owner/finance'
      fullPath: '/owner/finance'
      preLoaderRoute: typeof AuthenticatedOwnerFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/listings': {
      id: '/_authenticated/owner/listings'
      path: '/owner/listings'
      fullPath: '/owner/listings'
      preLoaderRoute: typeof AuthenticatedOwnerListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOwnerBookingsRoute: typeof AuthenticatedOwnerBookingsRoute
  AuthenticatedOwnerCustomersRoute: typeof AuthenticatedOwnerCustomersRoute
  AuthenticatedOwnerFinanceRoute: typeof AuthenticatedOwnerFinanceRoute
  AuthenticatedOwnerListingsRoute: typeof AuthenticatedOwnerListingsRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOwnerBookingsRoute: AuthenticatedOwnerBookingsRoute,
  AuthenticatedOwnerCustomersRoute: AuthenticatedOwnerCustomersRoute,
  AuthenticatedOwnerFinanceRoute: AuthenticatedOwnerFinanceRoute,
  AuthenticatedOwnerListingsRoute: AuthenticatedOwnerListingsRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
